services:
  frontend:
    image: hardenisthegoat/my-website-frontend-image:latest  # Use your prebuilt frontend image
    networks:
      - mynetwork

  backend:
    image: hardenisthegoat/my-website-backend-image:latest  # Use your prebuilt backend image
    ports:
      - "5000:5000"  # Expose backend on port 5000
    depends_on:
      - db
    volumes:
      - ./server/uploads:/app/uploads
    env_file:
      - server/.env  # Load environment variables
    networks:
      - mynetwork
    environment: 
      NODE_ENV: production  

  db:
    image: postgres:13  # Use the official Postgres image
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@ssword
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    image: nginx:latest  # Nginx service
    ports:
      - "80:80"  # Expose Nginx on port 80 (for frontend + API proxying)
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
      - ./client/build:/usr/share/nginx/html  # Serve frontend static files from here
      - /etc/letsencrypt/live/tankt78249.xyz:/etc/letsencrypt/live/tankt78249.xyz:ro
      - /etc/letsencrypt/archive/tankt78249.xyz:/etc/letsencrypt/archive/tankt78249.xyz:ro
    depends_on:
      - frontend
      - backend
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge